### PR TITLE
Add support for bare import declarations

### PR DESCRIPTION
**Pull request by jeapostrophe**

### CODE REVIEW

**Comment by jeapostrophe** [comment]
Any change requests for this?

**Comment by erikd** [comment]
I was hoping that @rhendric might review this. He's got some big plans and I would hope this does not interfere with that,

**Comment by rhendric** [comment]
Looks good to me!

**Comment by erikd** [comment]
Thanks!

**Comment by jeapostrophe** [comment]
Thank you!

**Pull request merged**
