### PR TITLE
Parentheses and parentheses-less Arrow expressions missing cases.

### PR DESCRIPTION
**Pull request by pedrofurla**
Notice, I think the cases for `_ => a` and `(_) => b` are missing too, or at least I couldn't figure how to implement these. Anyways, these are way down my priority list.

### CODE REVIEW

**Comment by diasbruno** [comment]
@pedrofurla I've added you as a collaborator on my fork, so we can keep it all in the same PR.

I'll try to make some progress this weekend.

**Comment by pedrofurla** [comment]
Oh, thought I had made PR into *your* branch.

**Comment by pedrofurla** [comment]
Done now. It now. Do you lurk around on #haskell IRC channel?

**Comment by diasbruno** [comment]
No, sorry. I'll check if I gave you the correct permissions so you can just push directly to the PRs branch.

**Comment by pedrofurla** [comment]
You did! *I* didn't want to :). I added a brief explanation on the reason in PR to your branch. You can always just accept it.

**Pull request closed without merging**
