### PR TITLE
Adding support for for..of and friends

### PR DESCRIPTION
**Pull request by flbulgarelli**
Hi!

This PR adds support for the following ES6 constructs: 

* `for (let x; ...;...)`
* `for (let x in ...)`
* `for (let x of ...)`
* `for (var x of ...)`
* `for (x of ...)`

Although these constructs are not listed in https://github.com/erikd/language-javascript/issues/71, I think this is part of the issue. I have added the three types of tests that are suggested there.

* I have modeled the `of` token in a similar fashion to `in`. However, only `in` is a true binary-operator, but I think there will be no issues with that :man_shrugging: 
* I have modeled the `for...of` control structure in a similar fashion to the current for-loops, but perhaps the AST may require a refactor in the future to avoid the cross product of all the `var/let/in/of` features :thinking: 

I hope everything is fine :pray: 

Thanks! :smile:

### CODE REVIEW

**Comment by erikd** [comment]
Very nice! Thanks!

**Comment by erikd** [comment]
Do you need this released to Hackage?

**Comment by flbulgarelli** [comment]
> Do you need this released to Hackage?

There is no hurry but that would be nice! 

Than you for the fast response.

**Comment by erikd** [comment]
New version published!

**Pull request merged**
