### PR TITLE
Version 0.6.0.14

### PR DESCRIPTION
**Pull request by erikd**

### CODE REVIEW

**Comment by hdgarrood** [comment]
Thanks for releasing this! I thought you might want to know that this release should probably have been `0.7`, not `0.6.0.14`, as it contains a few breaking changes (such as additions and removals of constructors). See eg https://github.com/purescript/purescript/issues/3737

**Comment by erikd** [comment]
Ah ok. I will release `0.7` over the weekend and deprecate `0.6.0.14`.

**Comment by hdgarrood** [comment]
Thanks!

**Comment by erikd** [comment]
I have already deprecated 0.6.0.14. Will release 0.7 today.

**Pull request merged**
